services:
  - type: web
    name: whatsapp-ai-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
